# Used by .github/workflows/ci-cd.yml as an extension to the main docker-compose.yml to run against a specific build image version
services:
  server:
    image: smartbear/git-en-boite:${GIT_EN_BOITE_IMAGE_VERSION}

  worker:
    image: smartbear/git-en-boite:${GIT_EN_BOITE_IMAGE_VERSION}

  smoke-tests:
    image: smartbear/git-en-boite:${GIT_EN_BOITE_IMAGE_VERSION}
