version: 2.1

orbs:
  node: circleci/node@2.0.0
  docker: circleci/docker@1.0.0

jobs:
  test-command-bus:
    docker:
      - image: circleci/node:14.0.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: packages/command-bus
          with-cache: true
          pkg-manager: yarn
      - run:
          name: Linting Typescript
          command: yarn run lint
          working_directory: packages/command-bus
      - run:
          name: Running tests
          command: yarn run test
          working_directory: packages/command-bus

  test-la-boite:
    docker:
      - image: circleci/node:14.0.0
        environment:
          DATABASE_URL: postgres://postgres@localhost/git-en-boite-test
          REDIS_URL: redis://localhost:6379
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_DB: git-en-boite-test
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: circleci/redis:5.0.9
    steps:
      - checkout
      - node/install-packages:
          app-dir: packages/la-boite
          with-cache: true
          pkg-manager: yarn
      - run:
          name: Linting Typescript
          command: yarn run lint
          working_directory: packages/la-boite
      - run:
          name: Running tests
          command: yarn run test
          working_directory: packages/la-boite

workflows:
  version: 2.1
  build:
    jobs:
      - test-la-boite
      - test-command-bus
      - docker/publish:
          image: smartbear/git-en-boite
          path: .
          tag: latest,stable
          before_build:
            - run:
                name: Creating container network
                command: docker network create git-en-boite
            - run:
                name: Creating postgres container ready for tests
                command: docker run --detach --network=git-en-boite --name postgres -h postgres -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_DB=git-en-boite-test postgres:12.2
            - run:
                name: Creating redis container ready for tests
                command: docker run --detach --network=git-en-boite --name redis -h redis redis:5.0.9
            - run:
                name: Writing .build-number file
                command: echo << pipeline.number >>#$(echo << pipeline.git.revision >> | cut -c 1-6) > packages/la-boite/.build-number
          after_build:
            - run:
                name: Running tests in container
                command: docker run --network=git-en-boite -e DATABASE_URL=postgres://postgres@postgres/git-en-boite-test -e REDIS_URL=redis://redis:6379 -i -t smartbear/git-en-boite:latest npm test
          filters:
            branches:
              only:
                - master
                - ci
