version: 2.1

orbs:
  node: circleci/node@2.0.0
  docker: circleci/docker@1.0.0

jobs:
  test-in-node:
    docker:
      - image: circleci/node:current
        environment:
          GIT_EN_BOITE_PG_URL: postgres://root@localhost/git-en-boite-test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: git-en-boite-test
      - image: circleci/redis:latest
    steps:
      - checkout
      - node/install-packages:
          app-dir: packages/la-boite
          with-cache: true
      - run:
          name: Compiling Typescript
          command: npx tsc
          working_directory: packages/la-boite
      - run:
          name: Linting Typescript
          command: npm run lint
          working_directory: packages/la-boite
      - run:
          name: Running tests
          command: ./bin/test
          working_directory: packages/la-boite

workflows:
  version: 2.1
  build:
    jobs:
      - test-in-node
      - docker/publish:
          image: smartbear/git-en-boite
          path: packages/la-boite
          tag: latest
          before_build:
            - run: 
                name: Creating container network
                command: docker network create git-en-boite
            - run: 
                name: Creating postgres container ready for tests
                command: docker run --detach --network=git-en-boite --name postgres -h postgres -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_DB=git-en-boite-test postgres
            - run:
                name: Creating redis container ready for tests
                command: docker run --detach --network=git-en-boite --name redis -h redis redis:latest
            - run:
                name: Writing .build-number file
                command: echo $CIRCLE_BUILD_NUM > packages/la-boite/.build-number
          after_build:
            - run: 
                name: Running tests in container
                command: docker run --network=git-en-boite -e GIT_EN_BOITE_PG_URL=postgres://postgres@postgres/git-en-boite-test -e REDIS_URL=redis://redis:6379 -i -t smartbear/git-en-boite:latest npm test
          filters:
            branches:
              only: 
                - master
                - ci
